# Generated by Django 2.2 on 2020-07-08 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppermallApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homegoods',
            name='GoodsPhoto',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
