# Generated by Django 2.2 on 2020-07-14 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppermallApp', '0002_auto_20200708_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.SmallIntegerField(default=750, null=True)),
                ('height', models.SmallIntegerField(default=390, null=True)),
                ('title', models.CharField(max_length=150)),
                ('imageUrl', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('imageUrl', models.CharField(max_length=100)),
            ],
        ),
    ]
